version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-2.10.7
      - test-2.11.12
      - test-2.12.6
jobs:
  test-2.10.7: &test-template
    docker:
      # specify the version you desire here
      - image: webpackcontrib/circleci-jdk9-node8

    environment: &test-env
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SBT_VERSION: 1.0.0
      SCALA_VERSION: 2.10.7

    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Compile & Test
          command: |
                    wget -q https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
                    sudo dpkg -i sbt-$SBT_VERSION.deb
                    cat /dev/null | sbt ++$SCALA_VERSION test:compile
                    cat /dev/null | sbt ++$SCALA_VERSION test:test

  test-2.11.12:
    <<: *test-template
    environment:
      <<: *test-env
      SCALA_VERSION: 2.11.12

  test-2.12.6:
    <<: *test-template
    environment:
      <<: *test-env
      SCALA_VERSION: 2.12.6
